# Generated by Django 5.2.6 on 2025-10-13 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='worker',
            field=models.ForeignKey(help_text='Выберите сотрудника, который будет назначен на этот посадочный выход', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
