# Generated by Django 5.2.6 on 2025-10-13 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_alter_gate_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number',
            field=models.IntegerField(default=1488, help_text='Введите номер рейса', max_length=5, verbose_name='Номер рейса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkindesk',
            name='worker',
            field=models.OneToOneField(blank=True, help_text='Выберите сотрудника, который будет назначен на эту стойку', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Выберите сотрудника, который будет назначен на этот посадочный выход', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
