# Generated by Django 5.2.6 on 2025-10-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_flight_number_alter_checkindesk_worker_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flight',
            name='planned_departure_or_planned_arrival_only_filled',
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.IntegerField(help_text='Введите номер рейса', verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='planned_arrival',
            field=models.DateTimeField(blank=True, help_text='Введите планируемое время прибытия (если рейс прибывает в данный аэропорт)', null=True, verbose_name='Запланированное время прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='planned_departure',
            field=models.DateTimeField(blank=True, help_text='Введите планируемое время вылета (если рейс вылетает из данного аэропорта)', null=True, verbose_name='Запланированное время вылета'),
        ),
        migrations.AlterUniqueTogether(
            name='checkindeskflight',
            unique_together={('desk', 'flight')},
        ),
    ]
