# Generated by Django 5.2.6 on 2025-10-14 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_remove_flight_planned_departure_or_planned_arrival_only_filled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindesk',
            name='worker',
            field=models.OneToOneField(blank=True, help_text='Выберите сотрудника, который будет назначен на эту стойку', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='id',
            field=models.OneToOneField(help_text='Выберите рейс, для которого будут назначены указанные временные метки', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbapp.flight', verbose_name='Рейс'),
        ),
    ]
