# Generated by Django 5.2.6 on 2025-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_alter_checkindesk_worker_alter_flighttime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Введите отчество пассажира (если имеется)', max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
